#!/bin/bash 
docker pull kenandervisagic/vim-container
wget 'https://raw.githubusercontent.com/kenandervisagic/vim-dark-mode/main/vim-dark-kenan/start_container' -O /usr/local/bin/start_container && chmod +x /usr/local/bin/start_container
wget 'https://raw.githubusercontent.com/kenandervisagic/vim-dark-mode/main/vim-dark-kenan/start_container_root' -O /usr/local/bin/start_container_root && chmod +x /usr/local/bin/start_container_root
wget 'https://github.com/kenandervisagic/vim-dark-mode/raw/main/vim-dark-kenan/bin/fzy' -O /usr/local/bin/fzy && chmod +x /usr/local/bin/fzy
