#!/bin/bash

CONTAINER_USERNAME=$SUDO_USER
CONTAINER_GROUPNAME=`id -gn $SUDO_USER`
CONF='/opt/vim_files'

HOMEDIR='/home/'$CONTAINER_USERNAME
GROUP_ID=$SUDO_GID
USER_ID=999
LIST=$(docker images | tail -n +2 | cut -d " " -f1)
IMAGE=$(echo "$LIST" | fzy)
DI=$(sort <(echo "$LIST") <(echo "$IMAGE") | uniq -d)
[[ -z "$DI" ]] && echo "The selected image is not available!" && exit

create_user_cmd()
{
  echo \
    groupadd -f -g $GROUP_ID $CONTAINER_GROUPNAME '&&' \
    groupadd -f -g 57 kvm '&&' \
    useradd -u 999 -g $CONTAINER_GROUPNAME $CONTAINER_USERNAME '&&' \
    usermod -a -G kvm $CONTAINER_USERNAME '&&' \
    chown root:kvm /dev/kvm '&&' \
    echo "\"$CONTAINER_USERNAME ALL=(ALL) NOPASSWD:ALL\" >> /etc/sudoers.d/$CONTAINER_USERNAME" '&&' \
    mkdir --parent $HOMEDIR '&&' \
    mkdir -p '/mnt'$HOMEDIR '&&' \
    chown -R $CONTAINER_USERNAME:$CONTAINER_GROUPNAME $HOMEDIR '&&' \
    cp -n /etc/skel/.bashrc $HOMEDIR/
}

execute_as_cmd()
{
  echo \
    sudo -u $CONTAINER_USERNAME HOME=$HOMEDIR
}

full_container_cmd()
{
  echo "'$(create_user_cmd) && $(execute_as_cmd) $@'"
}

eval docker run \
    --cap-add=SYS_PTRACE \
    --security-opt=apparmor:unconfined \
    --security-opt=seccomp:unconfined \
    --rm=true \
    -ti \
    -v $HOME:$HOMEDIR \
    -v /etc/localtime:/etc/localtime \
    -e DISPLAY=$DISPLAY \
    -v $HOME/.Xauthority:$HOMEDIR/.Xauthority \
    --device /dev/kvm \
    -w="$PWD" \
    --net=host \
    $IMAGE \
    /bin/bash -ci $(full_container_cmd '/bin/bash --login')


